CREATE OR REPLACE PROCEDURE P_REGISTRA_UTENTE (
	V_NOME VARCHAR,
	V_COGNOME VARCHAR,
	V_USERNAME VARCHAR,
	V_PASSWORD VARCHAR,
	V_EMAIL VARCHAR,
	V_DATANASCITA DATE,
	V_RUOLO TIPORUOLO
) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO
	UTENTE (
		NOME,
		COGNOME,
		USERNAME,
		PASSWORD,
		EMAIL,
		DATANASCITA,
		RUOLO
	)
VALUES
	(
		V_NOME,
		V_COGNOME,
		V_USERNAME,
		V_PASSWORD,
		V_EMAIL,
		V_DATANASCITA,
		V_RUOLO
	);
	
END; 
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_LOTTO (
	V_TESSITURA TIPOTESSITURA,
	V_DIMENSIONI INT,
	V_PH DECIMAL,
	V_MORFOLOGIA TIPOMORFOLOGIA,
	V_ALTITUDINE INT,
	V_LOCALITA VARCHAR,
	V_COMUNE VARCHAR,
	V_PROVINCIA VARCHAR,
	V_CREATORE INT
) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO
	LOTTOCOLTIVABILE (
		TESSITURA,
		DIMENSIONI,
		PH,
		MORFOLOGIA,
		ALTITUDINE,
		LOCALITA,
		COMUNE,
		PROVINCIA,
		FK_IDPROPRIETARIO
	)
VALUES
	(
		V_TESSITURA,
		V_DIMENSIONI,
		V_PH,
		V_MORFOLOGIA,
		V_ALTITUDINE,
		V_LOCALITA,
		V_COMUNE,
		V_PROVINCIA,
		V_CREATORE
	);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_PROGETTO_STAGIONALE (
	V_NOMEPROGETTO VARCHAR,
	V_STAGIONEDIRIFERIMENTO STAGIONE,
	V_DURATA INT,
	V_DATAINIZIO DATE,
	V_STATOESECUZIONE STATO,
	V_CODLOTTO INT,
	V_CREATORE INT
) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO
	PROGETTOSTAGIONALE (
		NOMEPROGETTO,
		STAGIONEDIRIFERIMENTO,
		DURATA,
		DATAINIZIO,
		STATOESECUZIONE,
		FK_CODLOTTO,
		FK_CREATORE
	)
VALUES
	(
		V_NOMEPROGETTO,
		V_STAGIONEDIRIFERIMENTO,
		V_DURATA,
		V_DATAINIZIO,
		V_STATOESECUZIONE,
		V_CODLOTTO,
		V_CREATORE
	);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_ATTIVITA_SEMINA (
	V_DATATINIZIO DATE,
	V_DATAFINE DATE,
	V_METODOSEMINA TIPOSEMINA,
	V_QUANTITASEMI DECIMAL,
	V_COLTURA VARCHAR,
	V_PROGETTO INT,
	V_COLTIVATORE INT
) LANGUAGE PLPGSQL AS $$
DECLARE
V_CODATTIVITA INT;
BEGIN
INSERT INTO
	ATTIVITA (
	    STATOESECUZIONE,
		DATAINIZIO,
		DATAFINE,
		FK_COLTIVATORE,
		FK_PROGETTO
	)
VALUES
	(
		'PIANIFICATO',
		V_DATAINIZIO,
		V_DATAFINE,
		V_COLTIVATORE,
		V_PROGETTO
	)
RETURNING
	CODATTIVITA INTO V_CODATTIVITA;

INSERT INTO
	METODOSEMINA
VALUES
	(V_METODOSEMINA, V_CODATTIVITA);

INSERT INTO
	SEMINACOLTURA
VALUES
	(V_QUANTITASEMI, V_CODATTIVITA, V_COLTURA);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_ATTIVITA_IRRIGAZIONE (
	V_DATATINIZIO DATE,
	V_DATAFINE DATE,
	V_METODOIRRIGAZIONE TIPOIRRIGAZIONE,
	V_PROGETTO INT,
	V_COLTIVATORE INT
) LANGUAGE PLPGSQL AS $$
DECLARE V_CODATTIVITA INT;

BEGIN
INSERT INTO
	ATTIVITA (
		STATOESECUZIONE,
		DATAINIZIO,
		DATAFINE,
		FK_COLTIVATORE,
		FK_CODPROGETTO
	)
VALUES
	(
		'PIANIFICATO',
		V_DATAINIZIO,
		V_DATAFINE,
		V_COLTIVATORE,
		V_PROGETTO
	)
RETURNING
	CODATTIVITA INTO V_CODATTIVITA;

INSERT INTO
	IRRIGAZIONE
VALUES
	(V_METODOIRRIGAZIONE, V_CODATTIVITA);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_ATTIVITA_RACCOLTA (
	V_DATAINIZIO DATE,
	V_DATAFINE DATE,
	V_METODORACCOLTA TIPORACCOLTA,
	V_QUANTITAPREVISTA DECIMAL,
	V_COLTIVATORE INT,
	V_PROGETTO INT
) LANGUAGE PLPGSQL AS $$
DECLARE V_CODATTIVITA INT;

BEGIN
INSERT INTO
	ATTIVITA (
		STATOESECUZIONE,
		DATAINIZIO,
		DATAFINE,
		FK_COLTIVATORE,
		FK_CODPROGETTO
	)
VALUES
	(
		'PIANIFICATO',
		V_DATAINIZIO,
		V_DATAFINE,
		V_COLTIVATORE,
		V_PROGETTO
	)
RETURNING
	CODATTIVITA INTO V_CODATTIVITA;

INSERT INTO
	RACCOLTA
VALUES
	(
		V_METODORACCOLTA,
		V_QUANTITAPREVISTA,
		NULL,
		V_CODATTIVITA
	);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_NOTIFICA_ATTIVITAIMMINENTE (
	V_TIPOATTIVITAIMMINENTE VARCHAR,
	V_DESCRIZIONE VARCHAR,
	V_DATASCADENZA DATE,
	V_CREATORE INT,
	OUT V_CODNOTIFICA INT
) LANGUAGE PLPGSQL AS $$

BEGIN
INSERT INTO
	NOTIFICA (DATAINVIO,FK_CREATORE)
VALUES
	(CURRENT_DATE,V_CREATORE)
RETURNING
	CODNOTIFICA INTO V_CODNOTIFICA;

INSERT INTO
	ATTIVITAIMMINENTE (TIPOATTIVITAIMMINENTE, DESCRIZIONE, DATASCADENZA,FK_CODNOTIFICA)
VALUES
	(
		V_TIPOATTIVITAIMMINENTE,
		V_DESCRIZIONE,
		V_DATASCADENZA,
		V_CODNOTIFICA
	);

END;
$$;

CREATE OR REPLACE PROCEDURE P_REGISTRA_NOTIFICA_ANOMALIA (
	V_TIPOANOMALIA VARCHAR,
	V_DESCRIZIONE VARCHAR,
	V_GRAVITA LIVELLOGRAVITA,
	V_ESTENSIONE INT,
	V_CREATORE INT,
	OUT V_CODNOTIFICA INT
) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO
	NOTIFICA (DATAINVIO, FK_CREATORE)
VALUES
	(CURRENT_DATE, V_CREATORE)
RETURNING
	CODNOTIFICA INTO V_CODNOTIFICA;

INSERT INTO
	ANOMALIA (
		TIPOANOMALIA,
		DESCRIZIONE,
		GRAVITA,
		ESTENSIONE,
		FK_CODNOTIFICA
	)
VALUES
	(
		V_TIPOANOMALIA,
		V_DESCRIZIONE,
		V_GRAVITA,
		V_ESTENSIONE,
		V_CODNOTIFICA
	);

END;
$$;

CREATE OR REPLACE PROCEDURE P_INVIA_A_DESTINATARIO (V_ID_NOTIFICA INT, V_ID_DESTINATARIO INT) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO
	NOTIFICADESTINATARIO (FK_CODNOTIFICA, FK_DESTINATARIO, VISUALIZZATA)
VALUES
	(V_ID_NOTIFICA, V_ID_DESTINATARIO, FALSE);

END;
$$;

CREATE OR REPLACE PROCEDURE P_AVVIA_PROGETTO (V_CODPROGETTO INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE PROGETTOSTAGIONALE
SET
	STATOESECUZIONE = 'IN_CORSO'
WHERE
	CODPROGETTO = V_CODPROGETTO
	AND STATOESECUZIONE = 'PIANIFICATO';

END;
$$;

CREATE OR REPLACE PROCEDURE P_AVVIA_ATTIVITA (V_CODATTIVITA INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE ATTIVITA
SET
	STATOESECUZIONE = 'IN_CORSO'
WHERE
	CODATTIVITA = V_CODATTIVITA
	AND STATOESECUZIONE = 'PIANIFICATO';

END;
$$;

CREATE OR REPLACE PROCEDURE P_COMPLETA_PROGETTO (V_CODPROGETTO INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE PROGETTOSTAGIONALE
SET
	STATOESECUZIONE = 'COMPLETATO',
	DATAFINE = CURRENT_DATE
WHERE
	CODPROGETTO = V_CODPROGETTO
	AND STATOESECUZIONE = 'IN_CORSO';

END;
$$;

CREATE OR REPLACE PROCEDURE P_COMPLETA_ATTIVITA (V_CODATTIVITA INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE ATTIVITA
SET
	STATOESECUZIONE = 'COMPLETATO'
WHERE
	CODATTIVITA = V_CODATTIVITA
	AND STATOESECUZIONE = 'IN_CORSO';

END;
$$;

CREATE OR REPLACE PROCEDURE P_ANNULLA_PROGETTO (V_CODPROGETTO INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE PROGETTOSTAGIONALE
SET
	STATOESECUZIONE = 'ANNULLATO',
	DATAFINE = CURRENT_DATE
WHERE
	CODPROGETTO = V_CODPROGETTO
	AND STATOESECUZIONE IN ('PIANIFICATO', 'IN_CORSO');

UPDATE ATTIVITA
SET
	STATOESECUZIONE = 'ANNULLATO'
WHERE
	CODATTIVITA = V_CODATTIVITA
	AND STATOESECUZIONE IN ('PIANIFICATO', 'IN_CORSO');

END;
$$;

CREATE OR REPLACE PROCEDURE P_COMPLETA_RACCOLTA (V_CODATTIVITA INT, V_QUANTITAREALE DECIMAL) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE RACCOLTA
SET
	QUANTITAREALE = V_QUANTITAREALE
WHERE
	FK_CODATTIVITA = V_CODATTIVITA;

UPDATE ATTIVITA
SET
	STATOESECUZIONE = 'COMPLETATO'
WHERE
	V_CODATTIVITA = CODATTIVITA
	AND STATOESECUZIONE = 'IN_CORSO';

END;
$$;

CREATE OR REPLACE PROCEDURE P_NOTIFICA_VISUALIZZATA (V_CODNOTIFICA INT, V_IDUTENTE INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE NOTIFICADESTINATARIO
SET
	VISUALIZZATA = TRUE
WHERE
	FK_DESTINATARIO = V_IDUTENTE
	AND FK_CODNOTIFICA = V_CODNOTIFICA;

END;
$$;

CREATE OR REPLACE PROCEDURE P_DISATTIVA_LOTTO (V_CODLOTTO INT) LANGUAGE PLPGSQL AS $$
BEGIN
UPDATE LOTTOCOLTIVABILE
SET
	ATTIVO = FALSE
WHERE
	V_CODLOTTO = CODLOTTO;

END;
$$;

CREATE OR REPLACE PROCEDURE P_CANCELLA_PROGETTO (V_CODPROGETTO INT) LANGUAGE PLPGSQL AS $$
BEGIN
DELETE FROM PROGETTOSTAGIONALE
WHERE
	V_CODPROGETTO = CODPROGETTO;

END;
$$;

