DROP TYPE IF EXISTS TIPORUOLO CASCADE;

DROP TABLE IF EXISTS UTENTE CASCADE;

DROP TYPE IF EXISTS TIPOTESSITURA CASCADE;

DROP TYPE IF EXISTS TIPOMORFOLOGIA CASCADE;

DROP TABLE IF EXISTS LOTTOCOLTIVABILE CASCADE;

DROP TABLE IF EXISTS PROGETTOSTAGIONALE CASCADE;

DROP TYPE IF EXISTS STAGIONE CASCADE;

DROP TYPE IF EXISTS STATO CASCADE;

DROP TABLE IF EXISTS COLTIVATOREPROGETTO CASCADE;

DROP TABLE IF EXISTS COLTURA CASCADE;

DROP TABLE IF EXISTS ATTIVITA CASCADE;

DROP TYPE IF EXISTS TIPOSEMINA CASCADE;

DROP TYPE IF EXISTS TIPOIRRIGAZIONE CASCADE;

DROP TYPE IF EXISTS TIPORACCOLTA CASCADE;

DROP TABLE IF EXISTS SEMINA CASCADE;

DROP TABLE IF EXISTS SEMINACOLTURA CASCADE;

DROP TABLE IF EXISTS IRRIGAZIONE CASCADE;

DROP TABLE IF EXISTS RACCOLTA CASCADE;

DROP TYPE IF EXISTS LIVELLOGRAVITA CASCADE;

DROP TABLE IF EXISTS NOTIFICA CASCADE;

DROP TABLE IF EXISTS NOTIFICADESTINATARIO CASCADE;

DROP TABLE IF EXISTS ATTIVITAIMMINENTE CASCADE;

DROP TABLE IF EXISTS ANOMALIA CASCADE;

DROP TABLE IF EXISTS PROGETTOCOLTURA CASCADE;

CREATE TYPE TIPORUOLO AS ENUM(
	'PROPRIETARIO',
	'COLTIVATORE',
	'PROPRIETARIO_COLTIVATORE'
);

CREATE TABLE UTENTE (
	IDUTENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	COGNOME VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	DATANASCITA DATE NOT NULL,
	RUOLO TIPORUOLO NOT NULL
);

CREATE TYPE TIPOTESSITURA AS ENUM(
	'SABBIOSO',
	'ARGILLOSO',
	'LIMOSO',
	'MEDIO_IMPASTO'
);

CREATE TYPE TIPOMORFOLOGIA AS ENUM('PIANEGGIANTE', 'COLLINARE', 'MONTUOSO');

CREATE TABLE LOTTOCOLTIVABILE (
	CODLOTTO SERIAL PRIMARY KEY,
	TESSITURA TIPOTESSITURA NOT NULL,
	DIMENSIONI INT NOT NULL CHECK (DIMENSIONI BETWEEN 1000 AND 1000000),
	PH DECIMAL(2, 1) NOT NULL CHECK (PH BETWEEN 4.0 AND 9.0),
	MORFOLOGIA TIPOMORFOLOGIA NOT NULL,
	ALTITUDINE INT NOT NULL CHECK (ALTITUDINE BETWEEN -20 AND 3000),
	LOCALITA VARCHAR(50) NOT NULL,
	COMUNE VARCHAR(50) NOT NULL,
	PROVINCIA CHAR(2) NOT NULL CHECK (PROVINCIA = UPPER(PROVINCIA)),
	ATTIVO BOOLEAN NOT NULL DEFAULT TRUE,
	FK_IDPROPRIETARIO INT NOT NULL,
	FOREIGN KEY (FK_IDPROPRIETARIO) REFERENCES UTENTE (IDUTENTE)
);

CREATE TYPE STAGIONE AS ENUM(
	'INVERNO_PRIMAVERA',
	'PRIMAVERA_ESTATE',
	'AUTUNNO_INVERNO'
);

CREATE TYPE STATO AS ENUM(
	'PIANIFICATO',
	'IN_CORSO',
	'COMPLETATO',
	'ANNULLATO'
);

CREATE TABLE PROGETTOSTAGIONALE (
	CODPROGETTO SERIAL PRIMARY KEY,
	NOMEPROGETTO VARCHAR(50) NOT NULL,
	STAGIONEDIRIFERIMENTO STAGIONE NOT NULL,
	DURATA INT NOT NULL,
	DATAINIZIO DATE NOT NULL,
	DATAFINE DATE DEFAULT NULL,
	STATOESECUZIONE STATO NOT NULL,
	FK_CODLOTTO INT NOT NULL,
	FK_CREATORE INT NOT NULL,
	FOREIGN KEY (FK_CREATORE) REFERENCES UTENTE (IDUTENTE),
	FOREIGN KEY (FK_CODLOTTO) REFERENCES LOTTOCOLTIVABILE (CODLOTTO),
	CONSTRAINT STATO_COMPLETATO_PROGETTO CHECK (
		STATOESECUZIONE != 'COMPLETATO'
		OR (
			DATAFINE IS NOT NULL
			AND DATAFINE >= DATAINIZIO
		)
	),
	CONSTRAINT STATO_ANNULLATO_PROGETTO CHECK (
		STATOESECUZIONE != 'ANNULLATO'
		OR (
			DATAFINE IS NOT NULL
			AND (DATAFINE - DATAINIZIO) < DURATA
		)
	),
	CONSTRAINT DATA_FINE_VALIDA_PROGETTO CHECK (
		DATAFINE IS NULL
		OR (
			DATAFINE >= DATAINIZIO
			AND (
				STATOESECUZIONE = 'COMPLETATO'
				OR STATOESECUZIONE = 'ANNULLATO'
			)
		)
	)
);

CREATE TABLE COLTIVATOREPROGETTO (
	FK_COLTIVATORE INT NOT NULL,
	FK_CODPROGETTO INT NOT NULL,
	PRIMARY KEY (FK_COLTIVATORE, FK_CODPROGETTO),
	FOREIGN KEY (FK_CODPROGETTO) REFERENCES PROGETTOSTAGIONALE (CODPROGETTO),
	FOREIGN KEY (FK_COLTIVATORE) REFERENCES UTENTE (IDUTENTE)
);

CREATE TABLE COLTURA (
	CODCOLTURA VARCHAR(50) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL UNIQUE,
	SPECIE VARCHAR(50) NOT NULL,
	FAMIGLIA VARCHAR(50) NOT NULL,
	TEMPOMATURAZIONE INT NOT NULL CHECK (TEMPOMATURAZIONE > 0),
	DESTINAZIONEUSO VARCHAR(50) NOT NULL,
	PERIODOIDEALE VARCHAR(50) NOT NULL
);

CREATE TABLE PROGETTOCOLTURA (
	FK_CODPROGETTO INT NOT NULL,
	FK_CODCOLTURA VARCHAR(50) NOT NULL,
	PRIMARY KEY (FK_CODPROGETTO, FK_CODCOLTURA),
	FOREIGN KEY (FK_CODPROGETTO) REFERENCES PROGETTOSTAGIONALE (CODPROGETTO),
	FOREIGN KEY (FK_CODCOLTURA) REFERENCES COLTURA (CODCOLTURA)
);

CREATE TABLE ATTIVITA (
	CODATTIVITA SERIAL PRIMARY KEY,
	STATOESECUZIONE STATO NOT NULL,
	DATAINIZIO DATE NOT NULL,
	DATAFINE DATE NOT NULL,
	FK_COLTIVATORE INT NOT NULL,
	FK_CODPROGETTO INT NOT NULL,
	FOREIGN KEY (FK_COLTIVATORE) REFERENCES UTENTE (IDUTENTE),
	FOREIGN KEY (FK_CODPROGETTO) REFERENCES PROGETTOSTAGIONALE (CODPROGETTO) ON DELETE CASCADE,
	CONSTRAINT DATA_FINE_VALIDA_ATTIVITA CHECK (DATAFINE >= DATAINIZIO)
);

CREATE TYPE TIPOSEMINA AS ENUM('SPAGLIO', 'FILE', 'POSTARELLE', 'IDROSEMINA');

CREATE TYPE TIPOIRRIGAZIONE AS ENUM(
	'ASPERSIONE',
	'LOCALIZZATA',
	'SCORRIMENTO',
	'SOMMERSIONE'
);

CREATE TYPE TIPORACCOLTA AS ENUM('MANUALE', 'MECCANIZZATA', 'MECCANICA');

CREATE TABLE SEMINA (
	METODOSEMINA TIPOSEMINA NOT NULL,
	FK_CODATTIVITA INT PRIMARY KEY,
	FOREIGN KEY (FK_CODATTIVITA) REFERENCES ATTIVITA (CODATTIVITA) ON DELETE CASCADE
);

CREATE TABLE SEMINACOLTURA (
	QUANTITASEMI DECIMAL(10, 3) NOT NULL CHECK (QUANTITASEMI > 0),
	FK_CODATTIVITA INT NOT NULL,
	FK_CODCOLTURA VARCHAR(50) NOT NULL,
	PRIMARY KEY (FK_CODATTIVITA, FK_CODCOLTURA),
	FOREIGN KEY (FK_CODATTIVITA) REFERENCES SEMINA (FK_CODATTIVITA) ON DELETE CASCADE,
	FOREIGN KEY (FK_CODCOLTURA) REFERENCES COLTURA (CODCOLTURA)
);

CREATE TABLE IRRIGAZIONE (
	METODOIRRIGAZIONE TIPOIRRIGAZIONE NOT NULL,
	FK_CODATTIVITA INT PRIMARY KEY,
	FOREIGN KEY (FK_CODATTIVITA) REFERENCES ATTIVITA (CODATTIVITA) ON DELETE CASCADE
);

CREATE TABLE RACCOLTA (
	METODORACCOLTA TIPORACCOLTA NOT NULL,
	QUANTITAPREVISTA DECIMAL(10, 3) NOT NULL CHECK (QUANTITAPREVISTA > 0),
	QUANTITAREALE DECIMAL(10, 3) DEFAULT NULL CHECK (QUANTITAREALE > 0),
	FK_CODATTIVITA INT PRIMARY KEY,
	FK_CODCOLTURA VARCHAR(50) NOT NULL,
	FOREIGN KEY (FK_CODATTIVITA) REFERENCES ATTIVITA (CODATTIVITA) ON DELETE CASCADE,
	FOREIGN KEY (FK_CODCOLTURA) REFERENCES COLTURA (CODCOLTURA)
);

CREATE TYPE LIVELLOGRAVITA AS ENUM('BASSO', 'MEDIO', 'ALTO', 'CRITICO');

CREATE TABLE NOTIFICA (
	CODNOTIFICA SERIAL PRIMARY KEY,
	DATAINVIO DATE NOT NULL,
	FK_CREATORE INT NOT NULL,
	FOREIGN KEY (FK_CREATORE) REFERENCES UTENTE (IDUTENTE)
);

CREATE TABLE NOTIFICADESTINATARIO (
	FK_CODNOTIFICA INT NOT NULL,
	FK_DESTINATARIO INT NOT NULL,
	VISUALIZZATA BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (FK_CODNOTIFICA, FK_DESTINATARIO),
	FOREIGN KEY (FK_CODNOTIFICA) REFERENCES NOTIFICA (CODNOTIFICA),
	FOREIGN KEY (FK_DESTINATARIO) REFERENCES UTENTE (IDUTENTE) ON DELETE CASCADE
);

CREATE TABLE ATTIVITAIMMINENTE (
	TIPOATTIVITAIMMINENTE VARCHAR(50) NOT NULL,
	DESCRIZIONE VARCHAR(500) DEFAULT NULL,
	DATASCADENZA DATE NOT NULL,
	FK_CODNOTIFICA INT PRIMARY KEY,
	FOREIGN KEY (FK_CODNOTIFICA) REFERENCES NOTIFICA (CODNOTIFICA) ON DELETE CASCADE
);

CREATE TABLE ANOMALIA (
	TIPOANOMALIA VARCHAR(50) NOT NULL,
	DESCRIZIONE VARCHAR(500) DEFAULT NULL,
	GRAVITA LIVELLOGRAVITA NOT NULL,
	ESTENSIONE INT DEFAULT NULL CHECK (ESTENSIONE > 0),
	FK_CODNOTIFICA INT PRIMARY KEY,
	FOREIGN KEY (FK_CODNOTIFICA) REFERENCES NOTIFICA (CODNOTIFICA) ON DELETE CASCADE
);