DROP TRIGGER IF EXISTS TRG_PROPRIETARIO_LOTTO_VALIDO ON LOTTOCOLTIVABILE;

DROP TRIGGER IF EXISTS TRG_PROPRIETARIO_PROGETTO_VALIDO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_COLTIVATORE_PROGETTO_VALIDO ON COLTIVATOREPROGETTO;

DROP TRIGGER IF EXISTS TRG_DURATA_PROGETTO_VALIDA ON PROGETTOCOLTURA;

DROP TRIGGER IF EXISTS TRG_NO_SOVR_PROGETTI_LOTTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_PROGETTO_LOTTO_NON_ATTIVO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_STATO_PIANIFICATO_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_STATO_IN_CORSO_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_COLTIVATORE_ASSEGNATO_PROGETTO ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_COLTIVATORE_ATTIVITA_VALIDO ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_NO_SOVR_ATTIVITA_COLTIVATORE ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_STATO_PIANIFICATO_ATTIVITA ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_STATO_IN_CORSO_ATTIVITA ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_STATO_COMPLETATO_ATTIVITA ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_STATO_ANNULLATO_ATTIVITA ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_STATO_PIANIFICATO_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_STATO_IN_CORSO_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_COERENZA_RACCOLTA_COLTURA ON RACCOLTA;

DROP TRIGGER IF EXISTS TRG_DATA_INIZIO_RACCOLTA_VALIDA ON RACCOLTA;

DROP TRIGGER IF EXISTS TRG_COERENZA_SEMINA_DURATA ON SEMINACOLTURA;

DROP TRIGGER IF EXISTS TRG_QUANTITA_REALE_VALORIZZATA ON RACCOLTA;

DROP TRIGGER IF EXISTS TRG_ATTIVITA_OBBLIGATORIE_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_METODO_RACCOLTA_MONTAGNA ON RACCOLTA;

DROP TRIGGER IF EXISTS TRG_METODO_IRRIGAZIONE_MONTAGNA ON IRRIGAZIONE;

DROP TRIGGER IF EXISTS TRG_DURATA_ATTIVITA_PROGETTO ON ATTIVITA;

DROP TRIGGER IF EXISTS TRG_METODO_IRRIGAZIONE_PENDENZA ON IRRIGAZIONE;

DROP TRIGGER IF EXISTS TRG_COERENZA_ATTIVITA_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_COERENZA_TIPO_ATTIVITA_SEMINA ON SEMINA;

DROP TRIGGER IF EXISTS TRG_COERENZA_TIPO_ATTIVITA_IRRIGAZIONE ON IRRIGAZIONE;

DROP TRIGGER IF EXISTS TRG_COERENZA_TIPO_ATTIVITA_RACCOLTA ON RACCOLTA;

DROP TRIGGER IF EXISTS TRG_COMPLETAMENTO_ATTIVITA_PROGETTO ON PROGETTOSTAGIONALE;

DROP TRIGGER IF EXISTS TRG_COERENZA_TIPO_NOTIFICA_ATTIVITA_IMMINENTE ON ATTIVITAIMMINENTE;

DROP TRIGGER IF EXISTS TRG_COERENZA_TIPO_NOTIFICA_ANOMALIA ON ANOMALIA;

DROP TRIGGER IF EXISTS TRG_NOTIFICA_CREATA_PROPRIETARIO ON NOTIFICA;

DROP TRIGGER IF EXISTS TRG_NOTIFICA_INVIATA_COLTIVATORI ON NOTIFICADESTINATARIO;

DROP TRIGGER IF EXISTS TRG_DATA_SCADENZA_ATTIVITA_IMMINENTE ON ATTIVITAIMMINENTE;

CREATE OR REPLACE FUNCTION FN_PROPRIETARIO_LOTTO_VALIDO () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		UTENTE U
	WHERE
		NEW.FK_IDPROPRIETARIO = U.IDUTENTE
		AND U.RUOLO = 'COLTIVATORE'
) THEN RAISE EXCEPTION 'Errore: l''utente deve avere ruolo di proprietario o proprietario coltivatore.';

ELSE RETURN NEW;

END IF;

END;$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PROPRIETARIO_LOTTO_VALIDO BEFORE INSERT
OR
UPDATE ON LOTTOCOLTIVABILE FOR EACH ROW
EXECUTE FUNCTION FN_PROPRIETARIO_LOTTO_VALIDO ();

CREATE OR REPLACE FUNCTION FN_PROPRIETARIO_PROGETTO_VALIDO () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		UTENTE U
	WHERE
		NEW.FK_CREATORE = U.IDUTENTE
		AND U.RUOLO = 'COLTIVATORE'
) THEN RAISE EXCEPTION 'Errore: l''utente deve avere ruolo di proprietario o proprietario coltivatore.';

ELSE RETURN NEW;

END IF;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PROPRIETARIO_PROGETTO_VALIDO BEFORE INSERT
OR
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_PROPRIETARIO_PROGETTO_VALIDO ();

CREATE OR REPLACE FUNCTION FN_COLTIVATORE_PROGETTO_VALIDO () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		UTENTE U
	WHERE
		NEW.FK_COLTIVATORE = U.IDUTENTE
		AND U.RUOLO = 'PROPRIETARIO'
) THEN RAISE EXCEPTION 'Errore: l''utente deve avere ruolo di coltivatore o proprietario coltivatore.';

ELSE RETURN NEW;

END IF;

END;$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COLTIVATORE_PROGETTO_VALIDO BEFORE INSERT
OR
UPDATE ON COLTIVATOREPROGETTO FOR EACH ROW
EXECUTE FUNCTION FN_COLTIVATORE_PROGETTO_VALIDO ();

CREATE OR REPLACE FUNCTION FN_DURATA_PROGETTO_VALIDA () RETURNS TRIGGER AS $$
DECLARE V_TEMPO_MATURAZIONE INT;

V_DURATA INT;

V_NOME COLTURA.NOME % TYPE;

BEGIN
SELECT
	C.NOME INTO V_NOME
FROM
	COLTURA C
WHERE
	NEW.FK_CODCOLTURA = C.CODCOLTURA;

SELECT
	C.TEMPOMATURAZIONE INTO V_TEMPO_MATURAZIONE
FROM
	COLTURA C
WHERE
	C.CODCOLTURA = NEW.FK_CODCOLTURA;

SELECT
	PS.DURATA INTO V_DURATA
FROM
	PROGETTOSTAGIONALE PS
WHERE
	PS.CODPROGETTO = NEW.FK_CODPROGETTO;

IF V_DURATA < V_TEMPO_MATURAZIONE THEN RAISE EXCEPTION 'Errore: la durata è insufficiente affinchè la coltura % giunga a maturazione.',
V_NOME;

END IF;

IF V_DURATA > 180 THEN RAISE EXCEPTION 'Errore: la durata supera il limite massimo di 180 giorni.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_DURATA_PROGETTO_VALIDA BEFORE INSERT
OR
UPDATE ON PROGETTOCOLTURA FOR EACH ROW
EXECUTE FUNCTION FN_DURATA_PROGETTO_VALIDA ();

CREATE OR REPLACE FUNCTION FN_NO_SOVR_PROGETTI_LOTTO () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		PROGETTOSTAGIONALE PS
	WHERE
		PS.FK_CODLOTTO = NEW.FK_CODLOTTO
		AND PS.CODPROGETTO != NEW.CODPROGETTO
		AND PS.STATOESECUZIONE NOT IN ('COMPLETATO','ANNULLATO')
		AND (NEW.DATAINIZIO, NEW.DATAINIZIO + NEW.DURATA) OVERLAPS (
			PS.DATAINIZIO,
			COALESCE(PS.DATAFINE, PS.DATAINIZIO + PS.DURATA)
		)
) THEN RAISE EXCEPTION 'Errore: stai tentando di utilizzare un lotto già impegnato in un altro progetto.';

ELSE RETURN NEW;

END IF;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_NO_SOVR_PROGETTI_LOTTO BEFORE INSERT
OR
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_NO_SOVR_PROGETTI_LOTTO ();

CREATE OR REPLACE FUNCTION FN_PROGETTO_LOTTO_NON_ATTIVO () RETURNS TRIGGER AS $$
DECLARE V_STATO_ATTIVO BOOLEAN;

BEGIN IF EXISTS (
	SELECT
		1
	FROM
		LOTTOCOLTIVABILE LC
	WHERE
		LC.CODLOTTO = NEW.FK_CODLOTTO
		AND LC.ATTIVO = FALSE
) THEN RAISE EXCEPTION 'Errore: non è possibile creare un progetto stagionale su di un lotto non più attivo.';

END IF;

RETURN NEW;

END; $$

LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PROGETTO_LOTTO_NON_ATTIVO BEFORE INSERT ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_PROGETTO_LOTTO_NON_ATTIVO ();

CREATE OR REPLACE FUNCTION FN_STATO_PIANIFICATO_PROGETTO () RETURNS TRIGGER AS $$
BEGIN IF NEW.STATOESECUZIONE = 'PIANIFICATO' THEN IF NEW.DATAINIZIO <= CURRENT_DATE THEN RAISE EXCEPTION 'Errore: un progetto pianificato deve avere la data di inizio nel futuro.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_PIANIFICATO_PROGETTO BEFORE INSERT
OR
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_STATO_PIANIFICATO_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_STATO_IN_CORSO_PROGETTO () RETURNS TRIGGER AS $$
BEGIN IF NEW.STATOESECUZIONE = 'IN_CORSO' THEN IF NEW.DATAINIZIO > CURRENT_DATE
OR NEW.DATAFINE IS NOT NULL THEN RAISE EXCEPTION 'Errore: un progetto in corso deve avere la data corrente maggiore della data di inizio.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_IN_CORSO_PROGETTO BEFORE INSERT
OR
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_STATO_IN_CORSO_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_COLTIVATORE_ASSEGNATO_PROGETTO () RETURNS TRIGGER AS $$

BEGIN
INSERT INTO
	COLTIVATOREPROGETTO
VALUES
	(NEW.FK_COLTIVATORE, NEW.FK_CODPROGETTO)
ON CONFLICT (FK_COLTIVATORE, FK_CODPROGETTO) DO NOTHING;

RETURN NEW;

END;$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COLTIVATORE_ASSEGNATO_PROGETTO
AFTER INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_COLTIVATORE_ASSEGNATO_PROGETTO ();

CREATE TRIGGER TRG_COLTIVATORE_ATTIVITA_VALIDO BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_COLTIVATORE_PROGETTO_VALIDO ();

CREATE OR REPLACE FUNCTION FN_NO_SOVR_ATTIVITA_COLTIVATORE () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
	WHERE
		A.FK_COLTIVATORE = NEW.FK_COLTIVATORE
		AND A.CODATTIVITA != NEW.CODATTIVITA
		AND A.STATOESECUZIONE NOT IN ('COMPLETATO','ANNULLATO')
		AND (NEW.DATAINIZIO, NEW.DATAFINE) OVERLAPS (A.DATAINIZIO, A.DATAFINE)
			
) THEN RAISE EXCEPTION 'Errore: sovrapposizione di periodi di attività per un coltivatore.';

ELSE RETURN NEW;

END IF;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_NO_SOVR_ATTIVITA_COLTIVATORE BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_NO_SOVR_ATTIVITA_COLTIVATORE ();

CREATE OR REPLACE FUNCTION FN_STATO_PIANIFICATO_ATTIVITA () RETURNS TRIGGER AS $$
BEGIN IF (NEW.STATOESECUZIONE = 'PIANIFICATO')
AND (NEW.DATAINIZIO <= CURRENT_DATE) THEN RAISE EXCEPTION 'Errore: un''attività pianificata deve iniziare nel futuro.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_PIANIFICATO_ATTIVITA BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_STATO_PIANIFICATO_ATTIVITA ();

CREATE OR REPLACE FUNCTION FN_STATO_IN_CORSO_ATTIVITA () RETURNS TRIGGER AS $$
BEGIN IF (NEW.STATOESECUZIONE = 'IN_CORSO')
AND (
	NEW.DATAINIZIO > CURRENT_DATE
	OR NEW.DATAFINE < CURRENT_DATE
) THEN RAISE EXCEPTION 'Errore: un''attivita in corso deve avere la data attuale (%) compresa tra % e %.',
CURRENT_DATE,
NEW.DATAINIZIO,
NEW.DATAFINE;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_IN_CORSO_ATTIVITA BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_STATO_IN_CORSO_ATTIVITA ();

CREATE OR REPLACE FUNCTION FN_STATO_COMPLETATO_ATTIVITA () RETURNS TRIGGER AS $$
BEGIN IF (NEW.STATOESECUZIONE = 'COMPLETATO')
AND (NEW.DATAFINE > CURRENT_DATE) THEN RAISE EXCEPTION 'Errore: un''attività completata ha la data di fine minore della data corrente.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_COMPLETATO_ATTIVITA BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_STATO_COMPLETATO_ATTIVITA ();

CREATE OR REPLACE FUNCTION FN_STATO_ANNULLATO_ATTIVITA () RETURNS TRIGGER AS $$
BEGIN IF (NEW.STATOESECUZIONE = 'ANNULLATO') THEN NEW.DATAFINE := CURRENT_DATE;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_STATO_ANNULLATO_ATTIVITA BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_STATO_ANNULLATO_ATTIVITA ();

CREATE OR REPLACE FUNCTION FN_COERENZA_RACCOLTA_COLTURA () RETURNS TRIGGER AS $$
DECLARE V_NOME COLTURA.NOME % TYPE;

BEGIN
SELECT
	C.NOME INTO V_NOME
FROM
	COLTURA C
WHERE
	C.CODCOLTURA = NEW.FK_CODCOLTURA;

IF NOT EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN PROGETTOCOLTURA PC ON PC.FK_CODPROGETTO = A.FK_CODPROGETTO
	WHERE
		NEW.FK_CODATTIVITA = A.CODATTIVITA
		AND NEW.FK_CODCOLTURA = PC.FK_CODCOLTURA
) THEN RAISE EXCEPTION 'Errore: la coltura ''%'' non fa parte del progetto associato all''attivita di raccolta',
V_NOME;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COERENZA_RACCOLTA_COLTURA BEFORE INSERT
OR
UPDATE ON RACCOLTA FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_RACCOLTA_COLTURA ();

CREATE OR REPLACE FUNCTION FN_DATA_INIZIO_RACCOLTA_VALIDA () RETURNS TRIGGER AS $$
DECLARE DATA_FINE_SEMINA ATTIVITA.DATAFINE % TYPE;

DATA_INIZIO_RACCOLTA ATTIVITA.DATAINIZIO % TYPE;

NOME_COLTURA COLTURA.NOME % TYPE;

BEGIN
SELECT
	MIN(A.DATAFINE) INTO DATA_FINE_SEMINA
FROM
	ATTIVITA A
	JOIN SEMINACOLTURA SC ON A.CODATTIVITA = SC.FK_CODATTIVITA
WHERE
	NEW.FK_CODCOLTURA = SC.FK_CODCOLTURA
	AND A.FK_CODPROGETTO = (
		SELECT
			FK_CODPROGETTO
		FROM
			ATTIVITA
		WHERE
			CODATTIVITA = NEW.FK_CODATTIVITA
	);

SELECT
	C.NOME INTO NOME_COLTURA
FROM
	COLTURA C
WHERE
	C.CODCOLTURA = NEW.FK_CODCOLTURA;

SELECT
	A.DATAINIZIO INTO DATA_INIZIO_RACCOLTA
FROM
	ATTIVITA A
WHERE
	NEW.FK_CODATTIVITA = A.CODATTIVITA;

IF DATA_INIZIO_RACCOLTA < DATA_FINE_SEMINA THEN RAISE EXCEPTION 'Errore: la raccolta non può iniziare prima della fine della semina di ''%''.',
NOME_COLTURA;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_DATA_INIZIO_RACCOLTA_VALIDA BEFORE INSERT
OR
UPDATE ON RACCOLTA FOR EACH ROW
EXECUTE FUNCTION FN_DATA_INIZIO_RACCOLTA_VALIDA ();

CREATE OR REPLACE FUNCTION FN_COERENZA_SEMINA_DURATA () RETURNS TRIGGER AS $$ 
DECLARE
V_TEMPO_MATURAZIONE INT;

V_DATA_FINE_SEMINA DATE;

V_DURATA_PROGETTO INT;

V_DATA_INIZIO_PROGETTO DATE;

V_NOME VARCHAR;
BEGIN
SELECT
	C.TEMPOMATURAZIONE,
	C.NOME INTO V_TEMPO_MATURAZIONE,
	V_NOME
FROM
	COLTURA C
	JOIN SEMINACOLTURA SC ON C.CODCOLTURA = SC.FK_CODCOLTURA
WHERE
	NEW.FK_CODATTIVITA = SC.FK_CODATTIVITA;

SELECT
	A.DATAFINE INTO V_DATA_FINE_SEMINA
FROM
	ATTIVITA A
WHERE
	A.CODATTIVITA = NEW.FK_CODATTIVITA;

SELECT
	PS.DURATA,
	PS.DATAINIZIO INTO V_DURATA_PROGETTO,
	V_DATA_INIZIO_PROGETTO
FROM
	PROGETTOSTAGIONALE PS
	JOIN ATTIVITA A ON PS.CODPROGETTO = A.FK_CODPROGETTO
WHERE
	A.CODATTIVITA = NEW.FK_CODATTIVITA;

IF (V_DATA_INIZIO_PROGETTO + V_DURATA_PROGETTO) < (V_DATA_FINE_SEMINA + V_TEMPO_MATURAZIONE) THEN RAISE EXCEPTION 'Errore: la data di fine semina selezionata non permetterà di far maturare la coltura ''%'' entro la fine del progetto stagionale.',
V_NOME;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COERENZA_SEMINA_DURATA BEFORE INSERT
OR
UPDATE ON SEMINACOLTURA FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_SEMINA_DURATA ();

CREATE OR REPLACE FUNCTION FN_QUANTITA_REALE_VALORIZZATA () RETURNS TRIGGER AS $$
DECLARE
BEGIN IF NEW.QUANTITAREALE IS NOT NULL THEN IF NOT EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
	WHERE
		A.CODATTIVITA = NEW.FK_CODATTIVITA
		AND A.STATOESECUZIONE = 'COMPLETATO'
) THEN RAISE EXCEPTION 'Errore: la quantità reale può essere valorizzata solo dopo il termine dell''attività di raccolta.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_QUANTITA_REALE_VALORIZZATA BEFORE INSERT
OR
UPDATE ON RACCOLTA FOR EACH ROW
EXECUTE FUNCTION FN_QUANTITA_REALE_VALORIZZATA ();

CREATE OR REPLACE FUNCTION FN_ATTIVITA_OBBLIGATORIE_PROGETTO () RETURNS TRIGGER AS $$
BEGIN IF NOT EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN SEMINA S ON A.CODATTIVITA = S.FK_CODATTIVITA
	WHERE
		NEW.CODPROGETTO = A.FK_CODPROGETTO
)
OR NOT EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN IRRIGAZIONE I ON A.CODATTIVITA = I.FK_CODATTIVITA
	WHERE
		NEW.CODPROGETTO = A.FK_CODPROGETTO
)
OR NOT EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN RACCOLTA R ON A.CODATTIVITA = R.FK_CODATTIVITA
	WHERE
		NEW.CODPROGETTO = A.FK_CODPROGETTO
) THEN RAISE EXCEPTION 'Errore: sul progetto stagionale vanno svolte almeno un''attività di semina, una di irrigazione e una di raccolta.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE CONSTRAINT TRIGGER TRG_ATTIVITA_OBBLIGATORIE_PROGETTO
AFTER INSERT
OR
UPDATE ON PROGETTOSTAGIONALE DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION FN_ATTIVITA_OBBLIGATORIE_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_METODO_RACCOLTA_MONTAGNA () RETURNS TRIGGER AS $$
BEGIN IF NEW.METODORACCOLTA = 'MECCANICA' THEN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN PROGETTOSTAGIONALE PS ON A.FK_CODPROGETTO = PS.CODPROGETTO
		JOIN LOTTOCOLTIVABILE LC ON PS.FK_CODLOTTO = LC.CODLOTTO
	WHERE
		A.CODATTIVITA = NEW.FK_CODATTIVITA
		AND LC.MORFOLOGIA = 'MONTUOSO'
) THEN RAISE EXCEPTION 'Errore: non si può praticare la raccolta meccanica sui lotti con morfologia montuosa.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_METODO_RACCOLTA_MONTAGNA BEFORE INSERT
OR
UPDATE ON RACCOLTA FOR EACH ROW
EXECUTE FUNCTION FN_METODO_RACCOLTA_MONTAGNA ();

CREATE OR REPLACE FUNCTION FN_METODO_IRRIGAZIONE_MONTAGNA () RETURNS TRIGGER AS $$
BEGIN IF NEW.METODOIRRIGAZIONE = 'SOMMERSIONE' THEN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
		JOIN PROGETTOSTAGIONALE PS ON A.FK_CODPROGETTO = PS.CODPROGETTO
		JOIN LOTTOCOLTIVABILE LC ON PS.FK_CODLOTTO = LC.CODLOTTO
	WHERE
		A.CODATTIVITA = NEW.FK_CODATTIVITA
		AND (
			LC.MORFOLOGIA = 'MONTUOSO'
			OR LC.MORFOLOGIA = 'COLLINARE'
		)
) THEN RAISE EXCEPTION 'Errore: non si può praticare l''irrigazione a sommersione sui lotti con morfologia collinare o montuosa.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_METODO_IRRIGAZIONE_PENDENZA BEFORE INSERT
OR
UPDATE ON IRRIGAZIONE FOR EACH ROW
EXECUTE FUNCTION FN_METODO_IRRIGAZIONE_MONTAGNA ();

CREATE OR REPLACE FUNCTION FN_DURATA_ATTIVITA_PROGETTO () RETURNS TRIGGER AS $$
DECLARE V_DURATA_PROGETTO INT;

V_DATA_INIZIO_PROGETTO DATE;

V_DATA_FINE_PROGETTO DATE;

BEGIN
SELECT
	PS.DURATA,
	PS.DATAINIZIO INTO V_DURATA_PROGETTO,
	V_DATA_INIZIO_PROGETTO
FROM
	PROGETTOSTAGIONALE PS
WHERE
	NEW.FK_CODPROGETTO = PS.CODPROGETTO;

V_DATA_FINE_PROGETTO := V_DATA_INIZIO_PROGETTO + V_DURATA_PROGETTO;

IF (NEW.DATAINIZIO < V_DATA_INIZIO_PROGETTO)
OR (NEW.DATAFINE > V_DATA_FINE_PROGETTO) THEN RAISE EXCEPTION 'Errore: l''attività non rientra nell''intervallo temporale del progetto.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_DURATA_ATTIVITA_PROGETTO BEFORE INSERT
OR
UPDATE ON ATTIVITA FOR EACH ROW
EXECUTE FUNCTION FN_DURATA_ATTIVITA_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_COERENZA_ATTIVITA_PROGETTO () RETURNS TRIGGER AS $$
BEGIN IF NEW.STATOESECUZIONE = 'ANNULLATO' THEN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
	WHERE
		A.FK_CODPROGETTO = NEW.CODPROGETTO
		AND A.STATOESECUZIONE != 'ANNULLATO'
) THEN RAISE EXCEPTION 'Errore: tutte le attività del progetto annullato devono essere annullate.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COERENZA_ATTIVITA_PROGETTO BEFORE
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_ATTIVITA_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_COERENZA_TIPO_ATTIVITA () RETURNS TRIGGER AS $$
BEGIN
  
    IF (TG_TABLE_NAME = 'semina') THEN
        IF EXISTS (SELECT 1 FROM irrigazione WHERE fk_codattivita = NEW.fk_codattivita) OR
           EXISTS (SELECT 1 FROM raccolta WHERE fk_codattivita = NEW.fk_codattivita) THEN
            RAISE EXCEPTION 'Errore: l''attività è già registrata come irrigazione o raccolta.';
        END IF;

   
    ELSIF (TG_TABLE_NAME = 'irrigazione') THEN
        IF EXISTS (SELECT 1 FROM semina WHERE fk_codattivita = NEW.fk_codattivita) OR
           EXISTS (SELECT 1 FROM raccolta WHERE fk_codattivita = NEW.fk_codattivita) THEN
            RAISE EXCEPTION 'Errore: l''attività è già registrata come semina o raccolta.';
        END IF;

   
    ELSIF (TG_TABLE_NAME = 'raccolta') THEN
        IF EXISTS (SELECT 1 FROM semina WHERE fk_codattivita = NEW.fk_codattivita) OR
           EXISTS (SELECT 1 FROM irrigazione WHERE fk_codattivita = NEW.fk_codattivita) THEN
            RAISE EXCEPTION 'Errore: l''attività è già registrata come semina o irrigazione.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COERENZA_TIPO_ATTIVITA_SEMINA BEFORE INSERT ON SEMINA FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_TIPO_ATTIVITA ();

CREATE TRIGGER TRG_COERENZA_TIPO_ATTIVITA_IRRIGAZIONE BEFORE INSERT ON IRRIGAZIONE FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_TIPO_ATTIVITA ();

CREATE TRIGGER TRG_COERENZA_TIPO_ATTIVITA_RACCOLTA BEFORE INSERT ON RACCOLTA FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_TIPO_ATTIVITA ();

CREATE OR REPLACE FUNCTION FN_COMPLETAMENTO_ATTIVITA_PROGETTO () RETURNS TRIGGER AS $$
BEGIN IF NEW.STATOESECUZIONE = 'COMPLETATO' THEN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITA A
	WHERE
		A.FK_CODPROGETTO = NEW.CODPROGETTO
		AND (
			A.STATOESECUZIONE = 'PIANIFICATO'
			OR A.STATOESECUZIONE = 'IN_CORSO'
		)
) THEN RAISE EXCEPTION 'Errore: non puoi completare il progetto, esistono ancora attività pianificate o in corso.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COMPLETAMENTO_ATTIVITA_PROGETTO BEFORE
UPDATE ON PROGETTOSTAGIONALE FOR EACH ROW
EXECUTE FUNCTION FN_COMPLETAMENTO_ATTIVITA_PROGETTO ();

CREATE OR REPLACE FUNCTION FN_COERENZA_TIPO_NOTIFICA () RETURNS TRIGGER AS $$
BEGIN IF (TG_TABLE_NAME = 'attivitaImminente') THEN IF EXISTS (
	SELECT
		1
	FROM
		ANOMALIA A
	WHERE
		A.FK_CODNOTIFICA = NEW.FK_CODNOTIFICA
) THEN RAISE EXCEPTION 'Errore: la notifica è già registrata come Anomalia.';

END IF;

ELSIF (TG_TABLE_NAME = 'anomalia') THEN IF EXISTS (
	SELECT
		1
	FROM
		ATTIVITAIMMINENTE A
	WHERE
		A.FK_CODNOTIFICA = NEW.FK_CODNOTIFICA
) THEN RAISE EXCEPTION 'Errore: la notifica è già registrata come Attività Imminente.';

END IF;

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_COERENZA_TIPO_NOTIFICA_ATTIVITA_IMMINENTE BEFORE INSERT
OR
UPDATE ON ATTIVITAIMMINENTE FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_TIPO_NOTIFICA ();

CREATE TRIGGER TRG_COERENZA_TIPO_NOTIFICA_ANOMALIA BEFORE INSERT
OR
UPDATE ON ANOMALIA FOR EACH ROW
EXECUTE FUNCTION FN_COERENZA_TIPO_NOTIFICA ();

CREATE OR REPLACE FUNCTION FN_NOTIFICA_CREATA_PROPRIETARIO () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		UTENTE U
	WHERE
		U.IDUTENTE = NEW.FK_CREATORE
		AND U.RUOLO = 'COLTIVATORE'
) THEN RAISE EXCEPTION 'Errore: un coltivatore non può creare notifiche.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_NOTIFICA_CREATA_PROPRIETARIO BEFORE INSERT ON NOTIFICA FOR EACH ROW
EXECUTE FUNCTION FN_NOTIFICA_CREATA_PROPRIETARIO ();

CREATE OR REPLACE FUNCTION FN_NOTIFICA_INVIATA_COLTIVATORI () RETURNS TRIGGER AS $$
BEGIN IF EXISTS (
	SELECT
		1
	FROM
		UTENTE U
	WHERE
		U.IDUTENTE = NEW.FK_DESTINATARIO
		AND U.RUOLO = 'PROPRIETARIO'
) THEN RAISE EXCEPTION 'Errore: non puoi inviare notifiche a proprietari.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_NOTIFICA_INVIATA_COLTIVATORI BEFORE INSERT ON NOTIFICADESTINATARIO FOR EACH ROW
EXECUTE FUNCTION FN_NOTIFICA_INVIATA_COLTIVATORI ();

CREATE OR REPLACE FUNCTION FN_DATA_SCADENZA_ATTIVITA_IMMINENTE () RETURNS TRIGGER AS $$
DECLARE V_DATA_INVIO DATE;

BEGIN
SELECT
	N.DATAINVIO INTO V_DATA_INVIO
FROM
	NOTIFICA N
WHERE
	N.CODNOTIFICA = NEW.FK_CODNOTIFICA;

IF V_DATA_INVIO > NEW.DATASCADENZA THEN RAISE EXCEPTION 'Errore: la data di scadenza è precedente alla data di invio.';

END IF;

RETURN NEW;

END; $$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_DATA_SCADENZA_ATTIVITA_IMMINENTE BEFORE INSERT
OR
UPDATE ON ATTIVITAIMMINENTE FOR EACH ROW
EXECUTE FUNCTION FN_DATA_SCADENZA_ATTIVITA_IMMINENTE ();